name: smooth_buy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  